# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "../../packer/base-centos7-virtualbox.box"
    config.vm.hostname = "centos7-dev"
    config.vm.network "private_network", :type => 'dhcp', :adapter => 2

    config.vm.provider "virtualbox" do |v|
        v.name = "centos7-dev"
        v.memory = 4096
        v.cpus = 2
    end
  end