# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "../../packer/jenkins-centos7-virtualbox.box"
    config.vm.hostname = "jenkins-centos7"
    config.vm.network "private_network", :type => 'dhcp', :adapter => 2

    config.vm.provider "virtualbox" do |v|
        v.name = "jenkins-centos7"
        v.memory = 8192
        v.cpus = 2
    end

    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "jenkins.yml"
    end
  end
